// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDXgJhNHoNbZZGW5RNKS8U2HNbwQeXW20',
    appId: '1:515037032433:web:05cb583577fae45bf45e50',
    messagingSenderId: '515037032433',
    projectId: 'strip-924b9',
    authDomain: 'strip-924b9.firebaseapp.com',
    storageBucket: 'strip-924b9.firebasestorage.app',
    measurementId: 'G-98X9B880SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKdWdFatkMYtd6dlchPdW2XipxqLE9Uc0',
    appId: '1:181527620299:android:5a154b6b8cb04b8584c94e',
    messagingSenderId: '181527620299',
    projectId: 'report-person-app',
    storageBucket: 'report-person-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7MywtsWoxQaJLUzrslUiTu67JHM3j6FA',
    appId: '1:181527620299:ios:fd7f387ef20c017484c94e',
    messagingSenderId: '181527620299',
    projectId: 'report-person-app',
    storageBucket: 'report-person-app.firebasestorage.app',
    iosBundleId: 'com.lthung.reportperson',
  );

}