// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_base/src/data/models/local/pending_purchase_model.dart';
import 'package:flutter_base/src/data/models/local/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CacheRoleAdapter());
    registerAdapter(PendingPurchaseCacheAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CacheRoleAdapter());
    registerAdapter(PendingPurchaseCacheAdapter());
    registerAdapter(UserAdapter());
  }
}
